#
# Key: `stages` (optional)
#
# The `stages` list contains a complete list of valid staging environments.  Defaults are dev, uat,
# prod.  If this configuration is removed you will need to add it back to enable additional stages.
#

stages:
  - dev
  - uat
  - prod

#
# Key: `vcs` (required)
#
# Defined settings for the version control system.  Currently only `git` is supported for the
# type.  The path can be any valid `git` URL -- you will need to ensure your deployment user can
# pull from the repo.
#

vcs:
  type: git
  path: git@github.com:symfony/demo.git

#
# Key: `db` (required)
#
# Define database settings for creating, exporting, and importing databases.
#

db:
  # Key: `type` (required) the type of database, e.g. `pgsql`, `mysql`
  type: pgsql

  # Key: `name` (required) the base name of the database, full database names will include stage
  # name and status, e.g. `dev_nmscpa_org`, `dev_nmscpa_org_old`
  name: nmscpa_org

  # Key: `role` (optional) the user role which owns newly created databases.  This should be equal
  # to the database user that connects from the application.  Defaults to `web` if undefined.
  role: web

  # Key: `user` (optional) the user role which can connect and manage databases.  This will default
  # to the default "root database user" for the database type if undefined.
  user: postgres

  # Key: `pass` (optional) the password for the `user`.
  pass:

#
# Key: 'env` (optional)
#
# A list of environment variables and their values.  These variables will be set on the environment,
# before any code execution and can be used to adjust behavior of supporting commands, e.g.
# `OPUS_DISABLED: 1`.
#

env:
  EXAMPLE_VAR: 1

#
# Key: `options` (optional)
#
# A list of deployment options and their values.  You can overload options on a particular stage
# by adding addtional `options` secitons suffixed by `-<stage>`.  For example, if you want to change
# the default branch on `uat` stage, you can do:
#
# options-uat:
#   branch: testing
#

options:
  # Key: `source` (optional) the stage which data/files are synced to upon deploy, default is `prod`
  source: prod

  # Key: `branch` (optional) is the branch to deploy, default varies on vcs type, `master` for `git`
  branch: master

share:
  - .env
  - writable

build:
  - npm install
  - gulp build
  - composer install

sync:
  - writable

release:
  - sudo service php7.3-fpm restart
